pothos-gui: reverse desktop file uninstall order

diff --git a/pothos-gui/Desktop/uninstall b/pothos-gui/Desktop/uninstall
--- a/pothos-gui/Desktop/uninstall
+++ b/pothos-gui/Desktop/uninstall
@@ -2,6 +2,22 @@
 
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
+echo -n "Uninstall Pothos GUI menu launcher...	"
+if [ -x /usr/bin/xdg-desktop-menu ] ; then
+    xdg-desktop-menu uninstall pothos-gui.desktop || true
+    echo "OK"
+else
+    echo "FAIL (missing xdg-desktop-menu)"
+fi
+
+echo -n "Uninstall Pothos GUI MIME types...	"
+if [ -x /usr/bin/xdg-mime ] ; then
+    xdg-mime uninstall ${DIR}/pothos-gui.xml || true
+    echo "OK"
+else
+    echo "FAIL (missing xdg-mime)"
+fi
+
 echo -n "Uninstall Pothos GUI icon resources...	"
 if [ -x /usr/bin/xdg-icon-resource ] ; then
     for context in mimetypes apps; do
@@ -13,20 +29,4 @@ if [ -x /usr/bin/xdg-icon-resource ] ; then
     echo "OK"
 else
     echo "FAIL (missing xdg-icon-resource)"
-fi
-
-echo -n "Uninstall Pothos GUI MIME types...	"
-if [ -x /usr/bin/xdg-mime ] ; then
-    xdg-mime uninstall ${DIR}/pothos-gui.xml || true
-    echo "OK"
-else
-    echo "FAIL (missing xdg-mime)"
-fi
-
-echo -n "Uninstall Pothos GUI menu launcher...	"
-if [ -x /usr/bin/xdg-desktop-menu ] ; then
-    xdg-desktop-menu uninstall pothos-gui.desktop || true
-    echo "OK"
-else
-    echo "FAIL (missing xdg-desktop-menu)"
 fi
